### ISSUE TITLE
Some observability features does not work when deploying a single composite

### ISSUE THREAD

**Issue by tharindulak** [wso2/cellery#1009]
**Description:**
In current observability implementation, when deploying a single composite following features are not working.
* Instances List 
* Instance Metrics
* Components List
* Component Metrics

**Suggested Assignees:**
@nadundesilva 

**Affected Product Version:**
CLI Version:		0.6.0-SNAPSHOT

**OS, DB, other environment details and versions:**    
MacOs 10.14.6 

**Steps to reproduce:**
Please deploy the following composite yaml.

```
apiVersion: "mesh.cellery.io/v1alpha2"
kind: "Composite"
metadata:
  annotations:
    mesh.cellery.io/cell-image-org: "choro"
    mesh.cellery.io/cell-image-name: "test"
    mesh.cellery.io/cell-image-version: "2.0.0"
    mesh.cellery.io/cell-dependencies: "[]"
  labels: {}
  name: "test"
  namespace: ns1
spec:
  components:
  - metadata:
      annotations: {}
      labels: {}
      name: "hello"
    spec:
      type: null
      template:
        containers:
        - image: "tharindulak/myrepo:app57f66451025102a27e0cfec64273f4c7"
          name: "hello"
          ports:
          - containerPort: 9090
      ports:
      - name: "hello"
        port: 80
        protocol: "http"
        targetContainer: "hello"
        targetPort: 9090
      configurations: []
      secrets: []
      volumeClaims: []
```
