### ISSUE TITLE
Unable to route traffic when two cells depend on the same cell 

### ISSUE THREAD

**Issue by Minoli** [wso2/cellery#929]
**Description:**
when two cells depend on the same cell the following error occurs. 

Minolis-MacBook-Pro:bin minta$ cellery route-traffic -d pet-be -t pet-be-as -p 50
✔ Starting to route 50% of traffic to instance pet-be-as
✔ Building modified rules
⠏ Applying modified ruleserror: error parsing ./pet-be-routing-artifacts.yaml: error converting YAML to JSON: yaml: line 2: mapping values are not allowed in this context
❌ Applying modified rules

Unable to route traffic to the target instance: pet-be-as, percentage: 50: exit status 1

------

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pet-fe--vs
spec:
  hosts:
  - pet-be--gateway-service
  http:
  - match:
    - authority:
        regex: ^(pet-be)(--gateway-service)(\S*)$
      headers:
        x-instance-id:
          exact: "1"
      sourceLabels:
        mesh.cellery.io.cell: pet-fe
        mesh.cellery.io.component: "true"
    route:
    - destination:
        host: pet-be--gateway-service
      weight: 50
    - destination:
        host: pet-be-as--gateway-service
      weight: 50
  - match:
    - authority:
        regex: ^(pet-be)(--gateway-service)(\S*)$
      headers:
        x-instance-id:
          exact: "2"
      sourceLabels:
        mesh.cellery.io.cell: pet-fe
        mesh.cellery.io.component: "true"
    route:
    - destination:
        host: pet-be--gateway-service
      weight: 50
    - destination:
        host: pet-be-as--gateway-service
      weight: 50
  - match:
    - authority:
        regex: ^(pet-be)(--gateway-service)(\S*)$
      sourceLabels:
        mesh.cellery.io.cell: pet-fe
        mesh.cellery.io.component: "true"
    route:
    - destination:
        host: pet-be--gateway-service
      weight: 50
    - destination:
        host: pet-be-as--gateway-service
      weight: 50
---
null
---
null
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pet-fe1--vs
spec:
  hosts:
  - pet-be--gateway-service
  http:
  - match:
    - authority:
        regex: ^(pet-be)(--gateway-service)(\S*)$
      headers:
        x-instance-id:
          exact: "1"
      sourceLabels:
        mesh.cellery.io.cell: pet-fe1
        mesh.cellery.io.component: "true"
    route:
    - destination:
        host: pet-be--gateway-service
      weight: 50
    - destination:
        host: pet-be-as--gateway-service
      weight: 50
  - match:
    - authority:
        regex: ^(pet-be)(--gateway-service)(\S*)$
      headers:
        x-instance-id:
          exact: "2"
      sourceLabels:
        mesh.cellery.io.cell: pet-fe1
        mesh.cellery.io.component: "true"
    route:
    - destination:
        host: pet-be--gateway-service
      weight: 50
    - destination:
        host: pet-be-as--gateway-service
      weight: 50
  - match:
    - authority:
        regex: ^(pet-be)(--gateway-service)(\S*)$
      sourceLabels:
        mesh.cellery.io.cell: pet-fe1
        mesh.cellery.io.component: "true"
    route:
    - destination:
        host: pet-be--gateway-service
      weight: 50
    - destination:
        host: pet-be-as--gateway-service
      weight: 50
---
null
---
null
```
